### ISSUE TITLE
Error: av_read_frame failed with 1094995529

### ISSUE THREAD

**Issue by DWCTOD** [SwinTransformer/Video-Swin-Transformer#72]
你好,我在使用的时候遇到一个问题, 参考 infer 的代码构造 data_loader ,加载视频文件,但是在处理到某个视频的时候报错了 
`decord._ffi.base.DECORDError: [16:51:53] /io/decord/src/video/video_reader.cc:432: Error: av_read_frame failed with 1094995529`

定位到的错误应该是这个
`mmaction/datasets/pipelines/loading.py", line 966, in __call__
    container = decord.VideoReader(file_obj, num_threads=self.num_threads)`
我对提示错误的视频进行测试,可以正常播放以及单独使用  decord.VideoReader 加载都是没有问题的, 现在就觉得很奇怪,不知道是否有空可以解答一下, 谢谢啦

**Comment by pp-jia** [comment]
我遇到了类似的问题，请问你现在有解决方法了吗？
